In [28]:
import numpy as np

In [29]:
my_arr = np.arange(1_000_000) ##O numpy é muito mais rápido e usa menos memoria

In [30]:
my_list = list(range(1_000_000))

In [31]:
%timeit my_arr2 = my_arr *2

937 μs ± 109 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
%timeit my_list2 = my_list * 2

11.2 ms ± 830 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]])

In [34]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [35]:
data*10 ## Executando uma operação sem loop

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [36]:
data + data ## Outra operacao sem loop

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [37]:
data.shape ## tamânho do array

(2, 3)

In [38]:
data.dtype ## tipo de dados do array 

dtype('float64')

In [39]:
## Creating ndarrays

In [40]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [41]:
arr1 = np.array(data2) ## transformacao de um array para um ndarray

In [52]:
arr1 ## um ndarray com 2 linhas e 4 colunas

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
type(arr1)

numpy.ndarray

In [46]:
arr1.ndim ##dimensoes

2

In [48]:
array2 = np.zeros(10)

In [49]:
array2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
array2.ndim

1

In [51]:
np.zeros((3,6)) ###

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
np.empty((2, 3, 2))

array([[[5.38967978e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [2.22809558e-312, 7.40331858e-038]],

       [[1.65503164e-047, 5.45510213e-066],
        [5.88839214e-062, 5.26235760e-037],
        [3.38056518e-061, 6.23632113e-042]]])

In [69]:
arr1 = np.array([1,2,3], dtype=np.float64) ## definicao do tipo de dados do ndarray, isso garante uma resposta mais rápida

In [60]:
arr = np.array([1,2,3,4,5])

In [61]:
arr.dtype

dtype('int64')

In [66]:
float_arr = arr.astype(np.float64) ## outro modo  de definir o tipo

In [67]:
float_arr

array([1., 2., 3., 4., 5.])

In [68]:
float_arr.dtype

dtype('float64')

In [71]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)

In [72]:
int_array = np.arange(10)

In [73]:
calibers = np.array([.22, .270,.357,.380,.44,.50],dtype=np.float64)

In [74]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
##Operacoes aritiméticas

In [76]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [77]:
arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [79]:
arr*arr ##Vai multiplicar ele por ele mesmo

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [80]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [82]:
arr2 = np.array([[0., 4., 1.],[7., 2. , 12.]])

In [83]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [84]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [87]:
## Slice em array

In [88]:
arr = np.arange(10)

In [89]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[5]

np.int64(5)

In [91]:
arr[5:8] = 12

In [92]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [93]:
arr_slice = arr[5:8]

In [95]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [96]:
arr_slice

array([12, 12, 12])

In [99]:
arr_slice[1] = 12345 ## Essa mudanca vai refletir no array original

In [98]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [100]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [101]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
old_values = arr3d[0].copy()

In [104]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
arr3d[0] = 42

In [106]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])