In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000) ##O numpy é muito mais rápido e usa menos memoria

In [3]:
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr *2

743 μs ± 68.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = my_list * 2

11.5 ms ± 481 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]])

In [7]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data*10 ## Executando uma operação sem loop

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data ## Outra operacao sem loop

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
data.shape ## tamânho do array

(2, 3)

In [11]:
data.dtype ## tipo de dados do array 

dtype('float64')

In [12]:
## Creating ndarrays

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr1 = np.array(data2) ## transformacao de um array para um ndarray

In [15]:
arr1 ## um ndarray com 2 linhas e 4 colunas

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
type(arr1)

numpy.ndarray

In [17]:
arr1.ndim ##dimensoes

2

In [18]:
array2 = np.zeros(10)

In [19]:
array2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
array2.ndim

1

In [21]:
np.zeros((3,6)) ###

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[6.36525307e-310, 6.36525307e-310],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.50008929e+248]],

       [[4.31174539e-096, 9.80058441e+252],
        [1.23971686e+224, 1.05118842e-153],
        [9.03292329e+271, 9.08366793e+223]]])

In [23]:
arr1 = np.array([1,2,3], dtype=np.float64) ## definicao do tipo de dados do ndarray, isso garante uma resposta mais rápida

In [24]:
arr = np.array([1,2,3,4,5])

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64) ## outro modo  de definir o tipo

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)

In [30]:
int_array = np.arange(10)

In [31]:
calibers = np.array([.22, .270,.357,.380,.44,.50],dtype=np.float64)

In [32]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
##Operacoes aritiméticas

In [34]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [35]:
arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr*arr ##Vai multiplicar ele por ele mesmo

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [37]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr2 = np.array([[0., 4., 1.],[7., 2. , 12.]])

In [40]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [41]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [42]:
## Slice em array

In [43]:
arr = np.arange(10)

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

np.int64(5)

In [46]:
arr[5:8] = 12

In [47]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr_slice = arr[5:8]

In [49]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345 ## Essa mudanca vai refletir no array original

In [52]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [54]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
old_values = arr3d[0].copy()

In [57]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr3d[0] = 42

In [59]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_values

In [62]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[1][0]

array([7, 8, 9])

In [64]:
arr3d[1:2]## Slice de um array

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [66]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [67]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr1[0][:1]##vai selecionar apenas a primeira linha

array([[1, 2, 3]])

In [69]:
arr7 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
arr7[:2,1:] ##Vai selecionar as duas linhas e vai colocar a coluna apartir do indice 1 

array([[2, 3],
       [5, 6]])

In [71]:
arr7[:2, 1:]

array([[2, 3],
       [5, 6]])

In [72]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [73]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [74]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [75]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [76]:
names != "bob"

array([ True,  True,  True,  True,  True,  True,  True])

In [77]:
~(names == "Bob") ## esse "~" é a mesma coisa que "!" em javaScript

array([False,  True,  True, False,  True,  True,  True])

In [78]:
mask = (names == "Bob") | (names == "Will") ## Verifica se tem um ou outro

In [79]:
mask

array([ True, False,  True,  True,  True, False, False])

In [80]:
data[data<0] = 0

In [81]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [82]:
##Fancy indexing

In [83]:
arr = np.zeros((8,4))

In [84]:
for i in range(8):
    arr[i] = i

In [85]:
arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [86]:
arr[[4,3,0,6]] ## vai filtrar os arrays com esses indices

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [87]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [88]:
arr = np.arange(32).reshape((8,4)) # cria um arraynp com 8 linhas e 4 colunas

In [89]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr.T ## Troca de oito linhas para quatro e vice versa

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [91]:
np.dot(arr.T, arr) ## Multiplicação entre matrizes

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [92]:
arr.T @ arr ## Outra maneira de multiplicar matrizes, assim como o dot, não guarda o resultado

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [93]:
arr.swapaxes(0,1) ## Troca os eixos do array

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [94]:
## Pseudorandom Number Generation, realiza a randomizalção de números

In [95]:
samples = np.random.standard_normal(size=(4,4)) ##cria uma matriz random de 4 x 4, e é infinitamente mais rápido

In [96]:
samples

array([[ 2.23954339, -1.86600854, -0.82397204,  0.70002868],
       [ 0.00679256, -0.76353029,  0.12387237,  0.84546591],
       [ 0.23515485,  2.79571882,  0.14889263, -0.61160013],
       [-0.10289395,  0.97226184, -0.3737123 , -0.32106393]])

In [97]:
rng = np.random.default_rng(seed=12345)

In [98]:
data = rng.standard_normal((2,3))

In [99]:
type(rng)

numpy.random._generator.Generator

In [100]:
##Universal function

In [101]:
arr = np.arange(10)

In [102]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.sqrt(arr) ##vai tirar a raiz

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [105]:
x = rng.standard_normal(8)

In [106]:
y = rng.standard_normal(8)

In [107]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [108]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [109]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
x = rng.standard_normal(8)

In [111]:
y = rng.standard_normal(8)

In [112]:
np.maximum(x,y) ##Pega o número maximo de cada posicao

array([ 0.90291934,  0.8286332 , -0.15818926,  0.44948393, -1.34360107,
        0.54154683,  1.72473993,  2.61815943])

In [113]:
arr = rng.standard_normal(7)*5

In [114]:
arr

array([-6.14337493,  1.28778884,  1.56451459, -0.65405845,  6.3499156 ,
       -0.46481229, -0.33075445])

In [115]:
remainder, whole_part = np.modf(arr) ##Vai separar o numero inteiro do ponto flutuante

In [116]:
remainder

array([-0.14337493,  0.28778884,  0.56451459, -0.65405845,  0.3499156 ,
       -0.46481229, -0.33075445])

In [117]:
whole_part

array([-6.,  1.,  1., -0.,  6., -0., -0.])

In [118]:
np.add(arr, 1) ##Vai adicionar um a cada numero do npArray

array([-5.14337493,  2.28778884,  2.56451459,  0.34594155,  7.3499156 ,
        0.53518771,  0.66924555])

In [119]:
np.abs(arr) ##número absoludo 

array([6.14337493, 1.28778884, 1.56451459, 0.65405845, 6.3499156 ,
       0.46481229, 0.33075445])

In [120]:
np.square(arr) ## Vai elevar cada número ao quadrado

array([37.74105551,  1.6584001 ,  2.44770591,  0.42779246, 40.32142816,
        0.21605046,  0.1093985 ])

In [121]:
np.square(arr) ## Novamente eleva ao quadrado

array([37.74105551,  1.6584001 ,  2.44770591,  0.42779246, 40.32142816,
        0.21605046,  0.1093985 ])

In [122]:
np.sign(arr) ##Diz os pontos negativos e positivos

array([-1.,  1.,  1., -1.,  1., -1., -1.])

In [123]:
np.rint(arr) ##Arredonda para o inteiro mais próximo

array([-6.,  1.,  2., -1.,  6., -0., -0.])

In [124]:
np.subtract(arr,1) ## vai subtrair cada número por 1

array([-7.14337493,  0.28778884,  0.56451459, -1.65405845,  5.3499156 ,
       -1.46481229, -1.33075445])

In [125]:
np.divide(arr,2) ##divide o número pelo número indicado

array([-3.07168746,  0.64389442,  0.7822573 , -0.32702923,  3.1749578 ,
       -0.23240614, -0.16537722])

In [126]:
points = np.arange(-5,5,0.01)

In [127]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [128]:
xs, ys = np.meshgrid(points,points) ## crriacao de uma grade 2D

In [129]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]],
      shape=(1000, 1000))

In [130]:
points2 = np.array([1,2,3,4,5])

In [131]:
points2

array([1, 2, 3, 4, 5])

In [132]:
xs, ys = np.meshgrid(points2,points2)

In [133]:
xs



array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [134]:
ys

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [135]:
z = np.sqrt(xs**2 + ys**2)

In [136]:
z

array([[1.41421356, 2.23606798, 3.16227766, 4.12310563, 5.09901951],
       [2.23606798, 2.82842712, 3.60555128, 4.47213595, 5.38516481],
       [3.16227766, 3.60555128, 4.24264069, 5.        , 5.83095189],
       [4.12310563, 4.47213595, 5.        , 5.65685425, 6.40312424],
       [5.09901951, 5.38516481, 5.83095189, 6.40312424, 7.07106781]])

In [137]:
import matplotlib.pyplot as plt

In [138]:
## Expressing conditional logic as Array

In [139]:
xarr = np.array([1.1, 1.2, 1.3,1.4,1.5])

In [140]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [141]:
cond = np.array([True, False, True, True, False])

In [142]:
result = np.where(cond, xarr, yarr) ## funciona como se fosse um if ternário
##O primeiro parâmetro é a condicao, e os dois ultimos são os valores, o true seria o xarr, e o false o yarr

In [143]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [144]:
arr = rng.standard_normal((4, 4))

In [145]:
arr

array([[-1.10821447,  0.13595685,  1.34707776,  0.06114402],
       [ 0.0709146 ,  0.43365454,  0.27748366,  0.53025239],
       [ 0.53672097,  0.61835001, -0.79501746,  0.30003095],
       [-1.60270159,  0.26679883, -1.26162378, -0.07127081]])

In [146]:
arr > 0

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [147]:
np.where(arr > 0, 2, -2) ## Se for maior que zero será 2, e se for menor -2

array([[-2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2, -2,  2],
       [-2,  2, -2, -2]])

In [148]:
##Mathematical and Statistical Methods

In [149]:
arr = rng.standard_normal((5,4))

In [150]:
arr

array([[ 0.47404973, -0.41485376,  0.0977165 , -1.64041784],
       [-0.85725882,  0.68828179, -1.15452958,  0.65045239],
       [-1.38835995, -0.90738246, -1.09542531,  0.00714569],
       [ 0.5343599 , -1.06580785, -0.18147274,  1.6219518 ],
       [-0.31739195, -0.81581497,  0.38657902, -0.22363893]])

In [151]:
arr.mean()

np.float64(-0.28009086633254743)

In [152]:
np.mean(arr) ##soma todos os valores e divide pela quantidade

np.float64(-0.28009086633254743)

In [153]:
arr.mean(axis=1)


array([-0.37087634, -0.16826356, -0.84600551,  0.22725778, -0.24256671])

In [154]:
arr = np.array([[0,1,2],[3, 4, 5],[6,7,8]])

In [155]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
bools = np.array([False, False, True, False])

In [157]:
bools.any()##Verifica se existe algum valor é True nesse array

np.True_

In [158]:
bools.all() ##Se todos os valores forem true ele retorna True

np.False_

In [159]:
arr = rng.standard_normal(6)

In [160]:
arr

array([-7.01690809e-01, -1.79571318e+00,  8.18325622e-01, -5.71032902e-01,
        7.85525063e-04, -1.06364272e+00])

In [161]:
arr.sort()## Organiza os valores em ordem

In [162]:
arr

array([-1.79571318e+00, -1.06364272e+00, -7.01690809e-01, -5.71032902e-01,
        7.85525063e-04,  8.18325622e-01])

In [163]:
arr = rng.standard_normal((5,3))

In [164]:
arr


array([[ 1.3017145 ,  0.74787294,  0.98087591],
       [-0.11041869,  0.46791853,  0.89060715],
       [ 1.02300937,  0.31238339, -0.06190469],
       [-0.35947965, -0.74864398, -0.96547891],
       [ 0.36003466, -0.24455253, -1.99585661]])

In [165]:
arr.sort(axis=0) ## Organiza a coluna em ordem crescente

In [166]:
arr

array([[-0.35947965, -0.74864398, -1.99585661],
       [-0.11041869, -0.24455253, -0.96547891],
       [ 0.36003466,  0.31238339, -0.06190469],
       [ 1.02300937,  0.46791853,  0.89060715],
       [ 1.3017145 ,  0.74787294,  0.98087591]])

In [167]:
arr.sort(axis=1) ## Organiza as linhas em ordem crescente, sort faz uma copia, ele não altera o array original

In [168]:
arr

array([[-1.99585661, -0.74864398, -0.35947965],
       [-0.96547891, -0.24455253, -0.11041869],
       [-0.06190469,  0.31238339,  0.36003466],
       [ 0.46791853,  0.89060715,  1.02300937],
       [ 0.74787294,  0.98087591,  1.3017145 ]])

In [169]:
arr2 = np.array([5 -10, 7, 1,0, -3])

In [170]:
sorted_arr2 = np.sort(arr2)

In [171]:
sorted_arr2

array([-5, -3,  0,  1,  7])

In [172]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe","Alex"])

In [173]:
np.unique(names) ##Pega os unicos valores e coloca em ordem 

array(['Alex', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [174]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [175]:
np.isin(values, [2, 3, 6]) ## retorna um boolean array comparando o indice atual dos valores com o array passado

array([ True, False, False,  True,  True, False,  True])

In [176]:
arr1 = np.array([2,5,6,7,5,7,5,6])

In [177]:
arr2 = np.array([3,4,5,4,5,6,7,8])

In [178]:
np.intersect1d(arr1, arr2) ## cria um array que possui esses valores em ambos os arrays

array([5, 6, 7])

In [179]:
np.union1d(arr1, arr2) ## cria um array que possui esses valores em ambos os arrays

array([2, 3, 4, 5, 6, 7, 8])

In [180]:
np.isin(arr1, arr2) ##Verifica se cada arr1 contem no arr2 e retorna um array de boolean

array([False,  True,  True,  True,  True,  True,  True,  True])

In [181]:
np.setdiff1d(arr1,arr2) ## Verifica qual elemento em x que nao está em y

array([2])

In [182]:
np.setxor1d(arr1, arr2)

array([2, 3, 4, 8])

In [183]:
arr = np.arange(10)

In [184]:
np.save("some_array", arr)##Esse array será salvo no vscode

In [185]:
np.load("some_array.npy") ##Esse código lê o arquivo salvo com o array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
np.savez("array_archive.npz", a = arr, b =arr2) ##Podemos salvar multiplos arrays

In [187]:
arch = np.load("array_archive.npz")

In [188]:
arch["b"]

array([3, 4, 5, 4, 5, 6, 7, 8])

In [189]:
np.savez_compressed("arrays_compressed.npz", a=arr, n=arr2)

In [190]:
arch2 = np.load("arrays_compressed.npz")

In [191]:
arch2

NpzFile 'arrays_compressed.npz' with keys: a, n

In [192]:
## Linear Algebra

In [193]:
x = np.array([[1., 2., 3.],[4.,5.,6.]])

In [194]:
y = np.array([[6., 23.],[-1, 7], [8,9]])

In [195]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [196]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [197]:
x.dot(y) ## multiplicação da matriz x pela y

array([[ 28.,  64.],
       [ 67., 181.]])

In [198]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [199]:
x @ np.ones(3)

array([ 6., 15.])

In [206]:
x = np.array([[1., 2., 3.],[3.,2.,4.]])

In [211]:
y = np.array([[4., 5.], [3., 2.],[4.,5.]])

In [212]:
x.dot(y)

array([[22., 24.],
       [34., 39.]])

In [213]:
from numpy.linalg import inv, qr

In [214]:
x = rng.standard_normal((5,5))

In [215]:
x

array([[-0.15524762,  1.06383087, -0.27517157, -1.85333593, -0.12434193],
       [ 0.78497452,  0.2019986 , -0.42807444,  1.8482889 ,  1.89995289],
       [-0.09842503,  0.81344544,  0.39249439,  0.7814429 ,  1.45327152],
       [ 0.82018605,  0.08770534, -0.65350565, -0.81188688, -0.02553817],
       [ 1.15818454,  0.30052087,  0.05305665,  0.25727152,  0.03574286]])

In [218]:
mat = x.T @ x ## Transposta de x vezes x

In [219]:
mat


array([[ 2.6640709 ,  0.33333647, -0.8064859 ,  1.29374175,  1.38813088],
       [ 0.33333647,  1.93223807, -0.10130498, -0.95651441,  1.44216777],
       [-0.8064859 , -0.10130498,  0.84290361,  0.56971469, -0.19011926],
       [ 1.29374175, -0.95651441,  0.56971469,  8.18702786,  4.90768763],
       [ 1.38813088,  1.44216777, -0.19011926,  4.90768763,  5.73920976]])

In [220]:
inv(mat)

array([[  1.95024897,  -4.29084445,   4.29484047,  -3.19493313,
          3.48082459],
       [ -4.29084445,  14.5568127 , -11.98707765,  10.30263674,
        -11.82710032],
       [  4.29484047, -11.98707765,  12.14093633,  -8.92083064,
         10.00389509],
       [ -3.19493313,  10.30263674,  -8.92083064,   7.62674144,
         -8.63338921],
       [  3.48082459, -11.82710032,  10.00389509,  -8.63338921,
         10.01823173]])