In [3]:
import numpy as np

In [5]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5,3)

array([[0.63402902, 0.95660126, 0.64552478],
       [0.27255251, 0.52719033, 0.43825891],
       [0.48771095, 0.68141766, 0.03584468],
       [0.35315468, 0.98178584, 0.10999678],
       [0.33881838, 0.67063787, 0.56931478]])

In [20]:
np.random.randint(1,100,10)

array([63, 15, 29, 28, 17, 12, 85, 38, 63,  9])

In [21]:
arr = np.arange(25)

In [29]:
arr2 = np.arange(0,48,3).reshape(4,4)

In [30]:
arr2

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [31]:
arr2.max()

np.int64(45)

In [32]:
arr2.min()

np.int64(0)

In [35]:
arr2.dtype

dtype('int64')

In [36]:
arr1 = np.arange(0,11)

In [37]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr1[1:5]

array([1, 2, 3, 4])

In [40]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[1][2]

np.int64(30)

In [45]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
bool_arr = arr > 5 

In [48]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [54]:
arr_2d= np.linspace(0,5,10).reshape(5,2)

In [55]:
arr_2d[0][1] + 10

np.float64(10.555555555555555)

In [56]:
arr_2d

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])